name: Go

on:
  schedule:
    - cron: "0 5 2 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Display Go Version
        run: go version
      - name: Update MAC-DB
        run: go test utils_test.go
      - name: Git commit && Git tag
        run: |
          chmod +x ./git_push.sh
          ./git_push.sh